ALTER TABLE guilds ALTER COLUMN target_channel SET NOT NULL;
ALTER TABLE guilds ALTER COLUMN language SET NOT NULL;
ALTER TABLE guilds ALTER COLUMN be_verbose SET NOT NULL;
ALTER TABLE guilds ALTER COLUMN premium_level SET NOT NULL;
