on:
  push:
    paths-ignore:
      - "**.md"
      - "**.ftl"
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}

      - if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends mold clang pkgconf

      - if: matrix.target == 'armv7-unknown-linux-musleabihf'
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabihf mold clang pkgconf

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scripty_v2-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/scripty_v2
