on:
  push:
    paths-ignore:
      - "**.md"
      - "**.ftl"
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: clang
  RUSTFLAGS: "--cfg tokio_unstable -Clink-arg=-fuse-ld=mold -Zshare-generics=y"

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          sudo apt update
          sudo apt install -y mold clang pkgconf

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scripty_v2-x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/scripty_v2
